import type { Patient } from "../types";

function InfoRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex justify-between py-2 border-b border-slate-50 last:border-0">
      <span className="text-xs text-slate-400">{label}</span>
      <span className="text-xs font-medium text-slate-700 text-right max-w-[60%]">{value}</span>
    </div>
  );
}

function ScoreGauge({ label, score, color }: { label: string; score: number; color: string }) {
  return (
    <div className="text-center">
      <div className={`text-2xl font-bold ${color}`}>{score.toFixed(3)}</div>
      <div className="text-xs text-slate-400 mt-0.5">{label}</div>
      <div className="mt-2 w-full bg-slate-100 rounded-full h-2">
        <div className={`h-2 rounded-full ${color.replace("text-", "bg-")}`} style={{ width: `${score * 100}%` }} />
      </div>
    </div>
  );
}

export default function PatientModal({
  patient,
  onClose,
}: {
  patient: Patient;
  onClose: () => void;
}) {
  return (
    <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div
        className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
          <div>
            <h2 className="text-base font-bold text-slate-800">
              Patient #{patient.hadm_id}
            </h2>
            <p className="text-xs text-slate-400">
              {patient.age}y · {patient.gender} · {patient.admission_type} admission
            </p>
          </div>
          <div className="flex items-center gap-2">
            {patient.readmitted && (
              <span className="text-xs font-semibold text-red-600 bg-red-50 px-2 py-1 rounded-full">
                Readmitted within 30d
              </span>
            )}
            <button onClick={onClose} className="text-slate-400 hover:text-slate-600 text-lg leading-none px-2">
              ✕
            </button>
          </div>
        </div>

        <div className="p-6 space-y-5">
          {/* Score gauges */}
          <div className="grid grid-cols-2 gap-4 bg-slate-50 rounded-xl p-4">
            <ScoreGauge label={`Stage 1 (XGBoost · thr=${patient.stage1_threshold})`} score={patient.stage1_score} color="text-blue-600" />
            <ScoreGauge label={`Stage 2 calibrated · thr=${patient.stage2_threshold} (${patient.age_band})`} score={patient.stage2_score} color="text-violet-600" />
          </div>

          {/* Patient profile */}
          <div>
            <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Patient Profile</h3>
            <div className="bg-slate-50 rounded-xl px-4">
              <InfoRow label="Age group" value={patient.age_band} />
              <InfoRow label="Length of stay" value={`${patient.los_days} days`} />
              <InfoRow label="Charlson Comorbidity Index" value={`${patient.charlson_index} (${patient.n_comorbidities} conditions)`} />
              <InfoRow label="Prior admissions" value={patient.n_prior_admissions} />
              <InfoRow label="Days since last discharge" value={patient.days_since_last_discharge} />
              <InfoRow label="Came via ED" value={patient.came_via_ed ? "Yes" : "No"} />
              <InfoRow label="Discharged to facility" value={patient.discharged_to_facility ? "Yes (SNF/rehab)" : "Home"} />
              <InfoRow label="Last creatinine" value={patient.creatinine !== null ? `${patient.creatinine} mg/dL` : "N/A"} />
              <InfoRow label="Last WBC" value={patient.wbc !== null ? `${patient.wbc} ×10³/μL` : "N/A"} />
            </div>
          </div>

          {/* Stage 3 explanation */}
          <div>
            <div className="flex items-center gap-2 mb-2">
              <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
                Stage 3 — Clinical Explanation
              </h3>
              <span className="text-xs text-emerald-500 bg-emerald-50 px-2 py-0.5 rounded-full">
                phi4-mini
              </span>
            </div>
            <div className="bg-emerald-50 border border-emerald-100 rounded-xl px-4 py-3 text-sm text-slate-700 leading-relaxed">
              {patient.explanation}
            </div>
            <p className="text-xs text-slate-400 mt-1.5">
              Generated by a local LLM. For clinical review only — not a diagnosis or recommendation.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
